### ISSUE TITLE
Update process breaks app when double clicking and opening the app

### ISSUE THREAD

**Issue by btelintelo** [Squirrel/Squirrel.Mac#163] opened 2016-02-09 18:49 UTC
Here is what I'm seeing...please tell me why I'm crazy.

1.  User downloads my electron app on mac which has squirrel auto updating.
2.  Instead of dragging app to applications, user double clicks the app to open.
3.  Once open, an message pops up that says "An update is ready to install....type your password to allow this."  

Typing the password does nothing, the app doesn't update.  Now, if the user just double clicks to open, I wouldn't expect them to be able to auto update, the app isn't installed properly.  

The issue I see is that in the com.electron....ShipIt directory, when the user double clicks to open, 2 logs files get written: ShipIt_stderr.log and ShipIt_stdout.log.  But they get written as root, while ShipItState.plist is written as the currentuser.  I can only guess that this is the reason for the popup asking for a password, because if you install the application normally, those two log files are owned by the current user, and the update process works fine.  The terrible thing about this is, if a user double clicks and opens, then later installs the app normally into the applications directory, the app is still bricked from performing updates.  Those two log files are still owned by root.  And, to make matters slightly worse, the ShipIt helper process crashes and respawns itself every 2 seconds forever, even after the user close the app.

So I would hope there is some kind of fix for the issue.  Once a computer gets in that state, you have to sudo rm the log files after killing the ShipIt process.  NOT something I would want to tell anyone to do to resolve an issue.

**Comment by mdiep** [comment] 2016-02-09 18:53
> bricks computer

That's not [what brick means](https://en.wikipedia.org/wiki/Brick_(electronics)).

**Comment by btelintelo** [comment] 2016-02-09 20:33
Here are the errors every 2 seconds in stderr: Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f9f81703c40 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Application Support/com.electron.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f9f81703450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2016-02-08 16:46:57.969 ShipIt[52971:580078] ShipIt quitting

**Comment by emorikawa** [comment] 2016-03-11 15:52
Yes, I get the same behavior, and yes it permanently keeps people who do this on old versions!

I put more info about this on this related issue here: https://github.com/Squirrel/Squirrel.Mac/issues/151

**Comment by joshaber** [comment] 2016-06-01 17:41
Seems similar/a dupe of #151.

**Closed by joshaber** 2016-06-01 17:41 UTC
