### ISSUE TITLE
support .patch files

### ISSUE THREAD

**Issue by citrusui** [Squirrel/Squirrel.Mac#162] opened 2016-01-30 16:30 UTC
Rather than download a huge zip every time an app updates, why not use .patch files? [Homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/ruby.rb) seems to support them. The syntax would probably look like this:

```json
  "patches": {
    "1.0-1.0.1": "https://example.com/myapp/patches/v1.0-v1.0.1.patch",
    "1.0-1.0.2": "https://example.com/myapp/patches/v1.0-v1.0.2.patch",
  }
```

Bonuses:
- .patch files are trivial to make
- faster updates

Caveats:
- Windows doesn't support .patch files
- manually creating patches sucks, so you'd probably want to automate this process

**Comment by keithduncan** [comment] 2016-01-31 23:42
Thanks for opening this issue!

I had plans to support something like this using a new [`Accept`](https://github.com/Squirrel/Squirrel.Mac#update-json-format) type for the update request.

This can can be added in a simple, backwards compatible way by updating the Squirrel.Mac client to support requesting an `application/binary-patch` MIME type against the `url` field returned to it in the JSON response, and then applying different handling when an `application/binary-patch` was returned instead of an `application/zip`.

It would be up to the server then to return an _appropriate_ patch file for the client to update using. I’d find this preferable to making the client select between multiple patches, one of the tenants of Squirrel.Mac is that updates are server driven.

**Comment by joshaber** [comment] 2016-06-01 17:33
This is essentially a dupe of #5.

**Closed by joshaber** 2016-06-01 17:33 UTC
