### ISSUE TITLE
"The command is disabled and cannot be executed"

### ISSUE THREAD

**Issue by fancyydk** [Squirrel/Squirrel.Mac#189] opened 2016-10-31 22:36 UTC
In our Electron app, this error message was logged a couple of times for users on Mac OS X 10.10.5, 10.11.6, and 10.12. It seems the users were able to download the update successfully, but then the app failed to update. It's hard to tell exactly what caused this issue just by looking at the logs and I have not been able to reproduce it myself, but a quick Google search returns results related to ReactiveCocoa which Squirrel.Mac depends on.

Has anybody run into this issue at all?
electron/electron#7792

**Comment by joshaber** [comment] 2016-11-01 00:39
Most likely this is caused by trying to install an update that has been aborted, which is most likely caused by an error earlier on.

**Comment by fancyydk** [comment] 2016-11-02 22:28
Thank you for the reply. We currently do not provide a way to abort an update that's already begun. So if an update was aborted, it's probably due to network issues or some other external factors outside of the app. Is the error message "The command is disabled and cannot be executed" coming from Squirrel.Mac? Is there any more information around this error or in what context it occurs so we can respond in a more actionable way?

**Comment by joshaber** [comment] 2016-11-03 01:59
>Is the error message "The command is disabled and cannot be executed" coming from Squirrel.Mac?

ReactiveCocoa is the one responsible for that specific message, but the command it's referencing is from Squirrel.Mac.

>Is there any more information around this error or in what context it occurs so we can respond in a more actionable way?

I'd hope there'd be more information in the user's logs, but I can't say for certain.

**Comment by joshaber** [comment] 2017-02-02 03:47
Closing since it doesn't sound like a Squirrel.Mac problem.

**Closed by joshaber** 2017-02-02 03:47 UTC
