### ISSUE TITLE
AutoUpdate Error code = 13 Permission Denied

### ISSUE THREAD

**Issue by dsagal** [Squirrel/Squirrel.Mac#209] opened 2017-07-19 15:51 UTC
Copied from https://github.com/electron/electron/issues/9752

---
Hi, currently I am having problem with the autoupdate in electron application. Here is the case.

    The application is able to check for update and successfully downloaded the update
    The application quits and re-launch however the version is not updated
    I checkout into the ShipIt_stderr.log and here is what I got

2017-06-14 11:32:15.589 ShipIt[44423:915887] Beginning installation
2017-06-14 11:32:23.460 ShipIt[44423:915887] Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}
2017-06-14 11:32:23.460 ShipIt[44423:915887] ShipIt quitting
2017-06-14 11:32:23.550 ShipIt[44440:916130] Resuming installation attempt 2
2017-06-14 11:32:33.271 ShipIt[44440:916133] Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}
2017-06-14 11:32:33.271 ShipIt[44440:916133] ShipIt quitting
2017-06-14 11:32:33.331 ShipIt[44443:916501] Resuming installation attempt 3
2017-06-14 11:32:41.436 ShipIt[44443:916504] Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}
2017-06-14 11:32:41.436 ShipIt[44443:916504] ShipIt quitting
2017-06-14 11:32:41.552 ShipIt[44444:916571] Too many attempts to install, aborting update
2017-06-14 11:32:41.554 ShipIt[44444:916574] ShipIt quitting

    Electron version: 1.6.11
    Operating system: Mac OS X 10.12.5

Actually this issue never happened before and after I got my electron version updated, there is this issue happening. I try to downgrade my electron version to 1.4.15 and 1.6.6 and 1.6.10 but no luck the problem still persists.

--- 
I'll add that I'm having the same problem on Mac OS X 10.11.6, electron 1.6.2. Any suggestions for how it could be debugged in more detail would be appreciated too.

**Comment by joshaber** [comment] 2017-07-19 15:57
That looks like a duplicate of https://github.com/Squirrel/Squirrel.Mac/issues/157 or https://github.com/Squirrel/Squirrel.Mac/issues/131.

There's currently a PR open to hopefully fix it: https://github.com/Squirrel/Squirrel.Mac/pull/207

**Comment by dsagal** [comment] 2017-07-19 16:05
It's a different issue. I am an Admin user, and running the application that lives on my desktop. All files in the application being run and the bundle that gets downloaded and unpacked are owned by me.

It's great if the PR fixes it too, but it's not a duplicate of either #157 or #131.

Is there a version of Electron built with the PR that I could test?

**Comment by joshaber** [comment] 2017-07-19 16:08
Hrm, I'm not sure where a permission problem would come from then.

>Is there a version of Electron built with the PR that I could test?

Unfortunately no. You could make your own but there's not build provided yet.

**Comment by dsagal** [comment] 2017-07-19 21:21
I am guessing it is this line in `Squirrel/SQRLInstaller.m`:
```
if (removexattr(path, "com.apple.quarantine", XATTR_NOFOLLOW) != 0) {
```
with the issue being that some files in the zip archive are read-only, and this call fails with errno 13 (Permission Denied).

@joshaber: does this sound like a plausible theory?

**Comment by joshaber** [comment] 2017-07-19 21:24
Ah, interesting. That's a good theory!

**Comment by dsagal** [comment] 2017-07-19 21:43
Making all files user-writable (in the bundle containing the new version) fixes the issue! I think it makes more sense for files to be read-only, but it's an acceptable workaround.

What I do think is necessary in order to close the issue is to report to the log which path and operation are causing the error. It took me hours to find the cause.

**Comment by joshaber** [comment] 2017-07-20 13:00
Agreed! Opened https://github.com/Squirrel/Squirrel.Mac/pull/210 to address this.

**Closed** 2017-07-20 13:47 UTC

**Comment by dsagal** [comment] 2017-07-20 13:50
Thank you!!!

**Comment by joshaber** [comment] 2017-07-20 13:52
Thanks for all your help in debugging!
