### ISSUE TITLE
Problem with Electron auto update on OSX

### ISSUE THREAD

**Issue by epezhman** [Squirrel/Squirrel.Mac#179] opened 2016-06-24 15:17 UTC
Hey, I'm trying to implement auto update on my  electron app, it's working fine on Windows but on OSX I get `Update Check Failed`. here is my code:

```
var initDarwinWin32 = () => {

    if (process.platform === 'darwin') {
        feedURL = config.AUTO_UPDATE_OSX_BASE_URL
    }
    else if (process.platform === 'win32') {
        feedURL = config.AUTO_UPDATE_WIN_BASE_URL + (os.arch() === 'x64' ? '64' : '32')
    }

    autoUpdater.on(
        'error',
        (err) => log.error(`Update error: ${err.message}`)
    )

    autoUpdater.on(
        'checking-for-update',
        () => log('Checking for update')
    )

    autoUpdater.on(
        'update-available',
        () => log('Update available')
    )

    autoUpdater.on(
        'update-not-available',
        () => log('Update not available')
    )

    autoUpdater.on(
        'update-downloaded',
        (e, notes, name, date, url) => log(`Update downloaded: ${name}: ${url}`)
    )

    feedURL += '?v=' + config.APP_VERSION
    autoUpdater.setFeedURL(feedURL)
    autoUpdater.checkForUpdates()
}

```

The  `feedURL` is like `http://188.166.160.83/update_server/updates/latest/osx?v=0.1.14` and the server response is `{"url":"https://s3.eu-central-1.amazonaws.com/demand-manager-resources/updates/latest/osx/TUM Demand Manager-0.1.15-mac.zip"}` ,I'm using `electron v1.2.5` and `OSX El Capitan` and `electron-builder v5.7.0` to build and sign the code and I don't get any errors with code signing, where do you think the problem is? thanks

**Comment by arcman77** [comment] 2016-06-30 03:15
I'm also having this problem. The update-release server is giving a 304 status in my case, but the error is the same. You're certain its not being cached somewhere?

**Comment by epezhman** [comment] 2016-06-30 11:56
@arcman77 If you get 304 status the error is expected then, the response needs to have 200 status with the Url inside, 
What do you mean by being cached somewhere?

**Comment by arcman77** [comment] 2016-06-30 17:26
I meant if the app is caching the response of the update server, causing to always get a 304. However I just confirmed that even when the server gives a response of 200, with the url included it still errors out, just as you have experienced. What version of electron are you using?

**Comment by epezhman** [comment] 2016-06-30 17:31
I'm using `electron v1.2.5 `and `OSX El Capitan` and `electron-builder v5.7.0`, anyway the only thing I can think of might be some problem with code signing, How do you sign your code?

**Comment by Vj3k0** [comment] 2016-07-19 09:11
Updating will fail if your binaries are not signed. Make sure to read [electron-builder docs](https://github.com/electron-userland/electron-builder/wiki/Code-Signing). Also, updating will result in error if you are not running binary but development version (which is of course not signed).

If this doesn't help, not long ago I've had problem with updating on Mac and it turned out to be problem in response. I blogged about it [here](http://electron.rocks/auto-update-failing-on-mac-os/).

**Comment by Mercieral** [comment] 2016-07-26 13:23
Is this an issue if using a free self-signed Apple cert? If I receive a 204 from the server then the autoUpdater correctly shows that no update is available. However I am also getting 'update check failed' when there is an update available. I can confirm that I am receiving a valid URL, a 200 response status, and it is signing correctly (with my self-signed cert) as the autoUpdater starts without throwing an error. 

It may be an issue with the URL received from the server. If I am using a local URL for testing purposes until we have s3 set up, is '/Users/amercier/myCompany/myProject/electron/releases/...' valid as the response URL?

**Comment by paul321** [comment] 2016-09-14 13:42
We have the same problem with last OSX update the app stopped updating we were using Electron 1.2.6 for months and after the OSX update Squirrel is not working

**Comment by joshaber** [comment] 2016-09-14 13:47
Unfortunately this is really hard to debug without having a reproducible case.

**Comment by paul321** [comment] 2016-09-14 13:54
Here are some logs from Squirrel:


2016-07-29 21:27:15.069 ShipIt[1875:31758] Beginning installation
2016-07-29 21:27:15.678 ShipIt[1875:31759] Moved bundle from file:///Applications/Microstockr.app to file:///var/folders/vq/43p_cr8d4y3brgl2pzjvp9ch0000gp/T/com.electron.microstockr.ShipIt.Fn7s4W8f/Microstockr.app
2016-07-29 21:27:15.678 ShipIt[1875:31759] Moved bundle from file:///var/folders/vq/43p_cr8d4y3brgl2pzjvp9ch0000gp/T/com.electron.microstockr.ShipIt.AE6qySTz/Microstockr.app to file:///Applications/Microstockr.app
2016-07-29 21:27:15.745 ShipIt[1875:31759] Couldn't remove owned bundle at location file:///var/folders/vq/43p_cr8d4y3brgl2pzjvp9ch0000gp/T/com.electron.microstockr.ShipIt.AE6qySTz/Microstockr.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Microstockr.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/vq/43p_cr8d4y3brgl2pzjvp9ch0000gp/T/com.electron.microstockr.ShipIt.AE6qySTz/Microstockr.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2016-07-29 21:27:15.780 ShipIt[1875:31759] Installation completed successfully
2016-07-29 21:27:15.854 ShipIt[1875:31760] Application launched at file:///Applications/Microstockr.app
2016-07-29 21:27:15.855 ShipIt[1875:31760] ShipIt quitting

**Comment by joshaber** [comment] 2016-09-14 14:20
Unfortunately those logs don't give us much to go on. Without a reproducible example, I'm at a loss.

**Comment by paul321** [comment] 2016-09-14 18:24
Here is the same issue with Atom editor: 
https://github.com/atom/atom/issues/2860

**Comment by joshaber** [comment] 2016-09-14 18:27
That is being tracked in https://github.com/Squirrel/Squirrel.Mac/issues/157 and https://github.com/Squirrel/Squirrel.Mac/issues/131. If this is that issue, then let's close this.

**Comment by paul321** [comment] 2016-09-14 18:30
The thing is this issue only happened after last OSX update so it was working about a month ago

**Comment by paul321** [comment] 2016-09-23 09:34
It seems the problem is that we changed the codesign certificate that has other identity, the updater fails to install the new certificate :)

**Comment by joshaber** [comment] 2017-07-20 13:22
That sounds like how Squirrel is intended to be used. We validate updates by checking the new update with the signature for the existing app. This is to guard against man-in-the-middle or other impersonation attacks.

**Closed by joshaber** 2017-07-20 13:22 UTC
